name: diffuser
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip=21.3.1
- setuptools=58.0.4
- wheel=0.37.1
- patchelf
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - Cython<3.0
    - numpy
    - torch==1.9.1+cu111
    - gym==0.18.0
    - matplotlib==3.3.4
    - typed-argument-parser
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - einops
    - ffmpeg-python
    - pillow
    - tqdm
    - pandas
    - wandb
    - flax>=0.3.5
    - jax<=0.2.21
    - ray==2.0.0
    - crcmod
    - google-api-python-client
    - cryptography
    - gdown
   
